name: Example workflow for Python using Snyk
on:
  push:
    branches:
      - CTPROJECT-514-Snyk
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: scan-results/python.txt
